stages:
  - docker-build
  - docker-push
  - deploy-staging

variables:
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  IMAGE_NAME: "yosefnuragaw/fmoc-fe-mobile:$IMAGE_TAG"
  DOCKER_DRIVER: overlay2
  NEXT_PUBLIC_API_URL: http://localhost:8080/api

docker-build:
  stage: docker-build
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  script:
    - cd "$CI_PROJECT_DIR/fmoc-mobile-frontend"
    - echo "Building Docker Image..."
    - docker build --build-arg NEXT_PUBLIC_API_URL="$NEXT_PUBLIC_API_URL" -t $IMAGE_NAME . --file Dockerfile
  rules:
    - when: always

docker-push:
  stage: docker-push
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  dependencies:
    - docker-build
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "Pushing image..."
    - docker push $IMAGE_NAME

deploy-staging:
  stage: deploy-staging
  image: alpine:latest
  dependencies:
    - docker-push
  before_script:
    - apk add --no-cache openssh-client docker-cli
    - mkdir -p ~/.ssh
    - printf '%s\n' "$PRIVATE_KEY_STAGING" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$DEPLOY_HOST_STAGING" >> ~/.ssh/known_hosts
  script:
    - echo "Logging in to Docker Hub on remote host..."
    - ssh -o StrictHostKeyChecking=no "$DEPLOY_USER_STAGING@$DEPLOY_HOST_STAGING" "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin"
    - echo "Pulling latest image on remote host..."
    - ssh -o StrictHostKeyChecking=no "$DEPLOY_USER_STAGING@$DEPLOY_HOST_STAGING" "docker pull $IMAGE_NAME"
    - echo "Stopping and removing existing container (if any)..."
    - ssh -o StrictHostKeyChecking=no "$DEPLOY_USER_STAGING@$DEPLOY_HOST_STAGING" "docker stop nextjs-app || true && docker rm nextjs-app || true"
    - echo "Starting new container..."
    - ssh -o StrictHostKeyChecking=no "$DEPLOY_USER_STAGING@$DEPLOY_HOST_STAGING" "docker run -d --restart always --name nextjs-app -p 80:80 -p 3000:3000 -e NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL $IMAGE_NAME"
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
